/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bottle.glb -T 
Files: bottle.glb [7.51MB] > D:\Development\webDevelopment\eCommerce\Public\bottle-transformed.glb [599.86KB] (92%)
Author: hipoojan (https://sketchfab.com/hipoojan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/water-bottleflask-da564f6e99d244508d8ef3401c1204aa
Title: Water Bottle/Flask
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Bottle(props) {

  const { nodes, materials } = useGLTF('/bottle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bottle_StainlessSteel_0.geometry} material={materials.PaletteMaterial001} position={[0, 2.561, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Handle_LeatherStrap_0.geometry} material={materials.LeatherStrap} position={[1.142, 5.189, -0.011]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/bottle-transformed.glb')
