/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 keychain.glb -T 
Files: keychain.glb [1.48MB] > D:\Development\webDevelopment\eCommerce\Public\keychain-transformed.glb [214.56KB] (86%)
Author: lamborado (https://sketchfab.com/lamborado)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/radiant-keychain-343b868fd50646118b07b499e994622c
Title: Radiant Keychain
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Keychain(props) {
  const { nodes, materials } = useGLTF('/keychain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.combined} rotation={[-Math.PI / 2, 0, 0]} scale={1.05} />
    </group>
  )
}

useGLTF.preload('/keychain-transformed.glb')
