/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 light.glb -T 
Files: light.glb [839.73KB] > D:\Development\webDevelopment\eCommerce\Public\light-transformed.glb [77.11KB] (91%)
Author: LIGHTSTAR GROUP (https://sketchfab.com/LIGHT_STAR_GROUP)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/110514-occhio-lightstar-spotlight-5d6f8307d99248b69cca5655efa7f3e5
Title: 110514 Occhio Lightstar spotlight
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Light(props) {
  const { nodes, materials } = useGLTF('/light-transformed.glb')

  // const texture = useTexture('/screen.png')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1105xx_Occhio_Lightstar_Plastic_light_gray_0'].geometry} material={materials.PaletteMaterial001} position={[0, 121.973, 2.828]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['1105xx_Occhio_Lightstar_Yelow_LED_ceramika_0'].geometry} material={materials.PaletteMaterial002} position={[0, 121.973, 2.828]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['1105xx_Occhio_Lightstar_Glass_Clear_Fog_green_0'].geometry} material={materials.PaletteMaterial003} position={[0, 121.973, 2.828]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['1105xx_Occhio_Lightstar_Glass_Simple_Clear_0'].geometry} material={materials.PaletteMaterial004} position={[0, 121.973, 2.828]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/light-transformed.glb')
